[build]
  base = "."
  publish = "netlify-dist"
  command = "yarn grunt && mkdir -p netlify-dist/examples && cp examples/* netlify-dist/examples && cp -r dist ./netlify-dist"
  environment = { YARN_VERSION = "1.9.4" }


